inn_hunt/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("innovator.urls")),
    path('',include("usern.urls")),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

innovator/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from .import views

urlpatterns = [

   
   path("signup/",views.signup,name="signup"),
   path("login/",views.login,name="login"),
   path("home/<int:tok>/<user>",views.home,name="home"),
   path("create",views.create,name="create"),
   path("detail/<int:product_id>/<username>/",views.detail,name='detail'),
   path("subcriber/<int:product_id>/<username>/<creator>",views.subcriber,name='subcriber'),
   path("showsubs/<int:product_id>/<creator>",views.showsubs,name='showsubs'),
   path("commentmake/<int:product_id>/<username>",views.commentmake,name="commentmake"),
   path("commentshow/<int:product_id>/<creator>",views.commentshow,name="commentshow"),
   path("buytoken/<int:tok>/<username>",views.buytoken,name='buytoken'),
   path("tokendonate/<int:product_id>/<username>/<creator>",views.tokendonate,name="tokendonate"),
   path("todoadd/<int:product_id>/<creator>",views.todoadd,name="todoadd"),
   path("manageproject/<int:product_id>/<creator>",views.manageproject,name="manageproject"),
   path("managetodo/<int:product_id>/<creator>",views.managetodo,name="managetodo"),
   path("manageaccount/<int:product_id>/<creator>",views.manageaccount,name="manageaccount"),
   path("encash/<int:product_id>/<creator>/<key>",views.encash,name="encash"),
   path("encashstatus/<int:product_id>/<creator>",views.encashstatus,name="encashstatus"),
   path("loginadmin/",views.loginadmin,name="loginadmin"),
   path("signupadmin/",views.signupadmin,name="signupadmin"),
   path("adminpagekey/",views.adminpagekey,name="adminpagekey"),
   path("adminmain/<adminname>",views.adminmain,name="adminmain"),
   path("adminuprove/<adminname>",views.adminuprove,name="adminuprove"),
   path("remove/<adminname>",views.remove,name="remove"),

   


]

usern/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from .import views

urlpatterns = [
   
    path("signupn/",views.signupn,name="signupn"),
    path("loginn/",views.loginn,name="loginn"),
    path('',include("innovator.urls")),
]

innovator/models.py
from django.db import models
from usern.models import orduser
from django.contrib.auth.models import User

class invuser(models.Model):
	username = models.CharField(max_length=250)
	firstname = models.CharField(max_length=250)
	lastname = models.CharField(max_length=250)
	email = models.CharField(max_length=250)
	phone = models.CharField(max_length=100)
	address =  models.CharField(max_length=250)
	user_type = models.CharField(max_length=50,default="innovator")
	password1 = models.CharField(max_length=150)
	password2 = models.CharField(max_length=150)

	def __str__(self):
		return self.username


class product(models.Model):
	title = models.CharField(max_length=250)
	pub_date = models.DateTimeField()
	body = models.TextField()
	image = models.ImageField(upload_to='images/')
	icon = models.ImageField(upload_to='images/')
	prostatus = models.CharField(max_length=200)
	postedby = models.ForeignKey(invuser, on_delete=models.CASCADE)

	def __str__(self):
		return self.title

	def summary(self):
		return self.body[:100] + ' ...'

	def pub_date_pretty(self):
		return self.pub_date.strftime('%b %e %Y')



'''
class subcribe(models.Model):
    link = models.ForeignKey(invuser, on_delete=models.CASCADE)
    sub_username = models.CharField(max_length=200)
    ordinary_username = models.CharField(max_length=200)

    def __str__(self):          you can never return the foreignkey 
    	return self.sub_username
'''


class sub(models.Model):
	sub_username = models.ForeignKey(invuser, on_delete=models.CASCADE)
	ordinary_username = models.CharField(max_length=200)
	mix = models.CharField(max_length=200)

	def __str__(self):
		return self.mix


class comment(models.Model):
	conid = models.ForeignKey(product,on_delete=models.CASCADE)
	inusername = models.CharField(max_length=200)
	ordusername = models.CharField(max_length=200)
	commentz = models.CharField(max_length=500)

	def __str__(self):
		return self.commentz


class sitetrans(models.Model):
	holder = models.ForeignKey(orduser,on_delete=models.CASCADE)
	donateusername = models.CharField(max_length=200)
	transdate = models.DateTimeField()
	amount = models.IntegerField()
	key = models.IntegerField()

	def __str__(self):
		return self.donateusername



class invtokenacc(models.Model):
	inuser = models.ForeignKey(invuser,on_delete=models.CASCADE)
	husername = models.CharField(max_length=200)
	donateusername = models.ForeignKey(sitetrans,on_delete=models.CASCADE)
	amount = models.IntegerField()
	mixd = models.CharField(max_length=350)
	keyh = models.ForeignKey(product,on_delete=models.CASCADE)

	def __str__(self):
		return self.mixd



class todo(models.Model):
	title = models.CharField(max_length=350)
	creator = models.CharField(max_length=150)
	description = models.CharField(max_length=350)
	status = models.CharField(max_length=100)
	product = models.ForeignKey(product,on_delete=models.CASCADE)

	def __str__(self):
		return self.title


class admin_my(models.Model):
	username = models.CharField(max_length=250)
	firstname = models.CharField(max_length=100)
	email = models.CharField(max_length=250)
	phone = models.CharField(max_length=50)
	password1 = models.CharField(max_length=150)
	password2 = models.CharField(max_length=150)

	def __str__(self):
		return self.username


class encash_request(models.Model):
	user = models.ForeignKey(invuser,on_delete=models.CASCADE)
	product = models.ForeignKey(product,on_delete=models.CASCADE)
	status = models.CharField(max_length=150)
	account_number = models.IntegerField()

	def __int__(self):
		return self.account_number

innovator/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.http import HttpResponse
from .models import invuser
from .models import product
from .models import sub
from .models import comment 
from .models import sitetrans
from .models import invtokenacc
from .models import todo
from .models import admin_my
from .models import encash_request
from usern.models import orduser
from django.utils import timezone
from usern import views as vk
# Create your views here.



def signup(response):
	if response.method == "POST":
		if response.POST['username'] and response.POST['firstname'] and response.POST['lastname'] and response.POST['email'] and response.POST['phone'] and response.POST['address'] and response.POST['password1'] and response.POST['password2']:   
			usersign = invuser()
			chk = invuser.objects.values_list('username',flat="True")  #ls = invuser.objects.values_list('firstname',flat="True")
			username_recived = response.POST['username'] #return render(response,'innovator/signup.html', {'error':'user already exist'})

			if username_recived in chk:
				return render(response,'innovator/signup.html', {'error':'user already exist'})
			else:
				usersign.username = response.POST['username']
			
			usersign.firstname = response.POST['firstname']
			usersign.lastname = response.POST['lastname']
			usersign.email = response.POST['email']
			usersign.address = response.POST['address']
			usersign.phone = response.POST['phone']
			
			if response.POST['password1'] == response.POST['password2']:
				usersign.password1 = response.POST['password1']
				usersign.password2 = response.POST['password2']
			else:
				return render(response,'innovator/signup.html', {'error':'Both passwords must match'})
			usersign.save()
			return redirect('login')

		else:
			return render(response,'innovator/signup.html', {'error':'All field are required.'})
	else:
		return render(response,'innovator/signup.html')

   
	return render(response, 'innovator/signup.html')# {'user_info':user_info}


def login(response):
	#------------- USEFULL QUERY MANIPULATE DATA ----------
	# User.objects.get(username=request.POST['username'])
	# code to retrive a specfic element 
	# ch = invuser.objects.get(username="monis")
	# the related fields are now accessable 
	# ch.password1 
    # password = response.POST['password1']
    #from sample.models import Todolist,Item,user
	#ls = Todolist.objects.all()
	#ls = Todolist.objects.get(id=2)
	#user.objects.create(tasks=ls,user_name="monis")
	usersign = invuser()
	global tokken
	tokken = "pass"
	if response.method == "POST":
		try:
			userobj = invuser.objects.get(username=response.POST['username'])
		except Exception:
			return render(response,'innovator/login.html', {'error':'User name or password in not valid.'})


		if response.POST['username'] == str(userobj):
			if str(userobj.password1) == str(response.POST['password1']):
				global user
				user = userobj
				return redirect("/home/"+str(1)+str('/')+str(userobj))
			else:
				return render(response,'innovator/login.html', {'error':'User name or Password in not valid.'})

	return render(response, 'innovator/login.html')

global tok

def home(response,tok,user):

	if tok == 1:
		user_obj = invuser.objects.get(username=user)
	if tok == 2:
		user_obj = orduser.objects.get(username=user)
	
	global tokk 
	tokk = tok
	
	
	prod = product.objects.all()
	return render(response, 'innovator/home.html',{'user':user_obj,'product':prod,'tok':tok})



def create(response):
	try:
		print(tokken)
	except Exception:
		return redirect("/login",{'error':'you are not logged in '})

	

	if response.method == "POST":
		if response.POST['title'] and response.POST['body'] and response.POST['prostatus'] and response.FILES['icon'] and response.FILES['image']:
			prod = product()
			prod.title = response.POST['title']
			prod.body = response.POST['body']
			prod.icon = response.FILES['icon']
			prod.image = response.FILES['image']
			prod.prostatus = response.POST['prostatus']
			prod.pub_date = timezone.datetime.now()
			prod.postedby = user
			prod.save()
		return  redirect("/home/"+str(1)+str('/')+str(user))



	return render(response,'innovator/create.html',{'user':user})



def detail(response,product_id,username):
	if tokk == 1:
		pname = invuser.objects.get(username=username)
	elif tokk == 2:
		pname = orduser.objects.get(username=username)

	print(pname)

	prod = get_object_or_404(product,pk=product_id)
	return render(response,'innovator/detail.html',{'product':prod,'pname':pname,'tokk':tokk})


def subcriber(response,product_id,username,creator):

	uqmix = str(username) + str(creator) # used to ensure that there in no other similar name and same person does not subcribe twice
	subb = sub()
	mix_r_list = sub.objects.values_list('mix',flat="True")
	print(mix_r_list)

	if uqmix in mix_r_list:
		print("in condtion")
		return render(response,'innovator/error.html',{'error':'you have already subcribed ','product_id':product_id,'username':username})
	else:
		print(creator+" creator")
		print(username+" username")
		pcreator = invuser.objects.get(username=creator)
		subb.sub_username = pcreator
		subb.ordinary_username = username
		subb.mix = uqmix
		subb.save()
	return redirect("/detail/"+str(product_id)+str("/")+str(username))


'''
___________________ ACCESSING USING FOREIGN KEY________________________
from innovator.models import invuser
ls = invuser.objects.get(username="random_travel_boiii_o") / you have to know the exact name 
ks = ls.sub_set.all()
for i in ks:
	print(i)
	print(i.orinary_username)
 This took me about 30 mins to figure out and iam loosing my mind 

'''

def showsubs(response,product_id,creator):
	userobj = invuser.objects.get(username=creator)
	return render(response,'innovator/showsub.html',{'userobj':userobj})


def commentmake(response,product_id,username):
	com = comment()
	prod = product.objects.get(id=product_id)
	x = prod.postedby.username
	print(prod.id)
	if response.method == 'POST':
		if response.POST['commentz']:
			com.conid = prod
			com.inusername = prod.postedby.username
			com.ordusername = username
			com.commentz = response.POST['commentz']
			com.save()
			return redirect("/detail/"+str(product_id)+str("/")+str(username))
		else:
			return render(response,'innovator/commentmake.html', {'prod':prod,'username':username,'error':'All field are required'})
        
	else:
		return render(response,'innovator/commentmake.html',{'prod':prod,'username':username})


	return render(response,'innovator/commentmake.html',{'prod':prod,'username':username})


def commentshow(response,product_id,creator):
	print(product_id)
	prod = product.objects.get(id=product_id)
	creator = invuser.objects.get(username=creator)
	print(creator)

	return render(response,'innovator/commentshow.html',{'prod':prod,'creator':creator})



def buytoken(response,tok,username):
	user_obj = orduser.objects.get(username=username)
	tran = sitetrans()

	
	if response.method == 'POST':
		if response.POST['amount'] and response.POST['card_number'] and response.POST['expirydate'] and response.POST['CVV'] and response.POST['key']:
			int_amount = int(response.POST['amount']) #number input restriction
			int_card_number = int(response.POST['card_number'])
			int_key = int(response.POST['key'])
			int_CVV = int(response.POST['CVV'])
			flag_len_CVV = len(response.POST['CVV'])
			flag_len_key = len(response.POST['key'])
			flag_len_card_number = len(response.POST['card_number'])

			if flag_len_CVV != 3:
				return render(response,'innovator/buytoken.html',{'user_obj':user_obj,'tok':tok,'error':'Error CVV should  3 Digits '})

			if flag_len_key > 10:
				return render(response,'innovator/buytoken.html',{'user_obj':user_obj,'tok':tok,'error':'Key should not be greate than 10 digits '})

			if flag_len_key < 10:
				return render(response,'innovator/buytoken.html',{'user_obj':user_obj,'tok':tok,'error':'Key should not be less than  10 digits '})

			if flag_len_card_number != 16:
				return render(response,'innovator/buytoken.html',{'user_obj':user_obj,'tok':tok,'error':' Card number should be 16 digits  '})

			holder_r_list = sitetrans.objects.values_list('donateusername',flat="True") 
			print(holder_r_list)
			if username in holder_r_list:                                   
				update_obj = sitetrans.objects.get(donateusername=username)
				update_obj.amount = update_obj.amount + int_amount
				update_obj.save()
				return  redirect("/home/"+str(tok)+str('/')+str(username))
			else:        
				tran.holder = user_obj
				tran.donateusername = username
				tran.transdate = timezone.datetime.now()
				tran.amount = int_amount
				tran.key = int_key
				tran.save()
				return  redirect("/home/"+str(tok)+str('/')+str(username))



		else:
			return render(response,'innovator/buytoken.html',{'user_obj':user_obj,'tok':tok,'error':'All field are required'})
	else:
		return render(response,'innovator/buytoken.html',{'user_obj':user_obj,'tok':tok})

	return render(response,'innovator/buytoken.html',{'user_obj':user_obj,'tok':tok})


def tokendonate(response,product_id,username,creator):
	acc = invtokenacc()
	mixk = str(username) + str(creator) + str(product_id)
	donation_list = invtokenacc.objects.values_list('mixd',flat=True) #geting the list of existing user/inv pairs
	creator_obj = invuser.objects.get(username=creator) # inv user instance for foreign key
	product_obj = product.objects.get(id=product_id)
	tran_obj = sitetrans.objects.get(donateusername=username)
   

	if response.method == 'POST':
		if response.POST['amount'] and response.POST['key']:
			
			int_keyr_len = len(response.POST['key'])
			int_amount = int(response.POST['amount'])

			if int_keyr_len != 10:
				return render(response,'innovator/tokendonate.html',{'product_id':product_id,'username':username,'creator':creator,'error':'key should be 10 digits'})

			if mixk in donation_list:
				update_amount = invtokenacc.objects.get(mixd=mixk)
				tran_obj.amount = tran_obj.amount - int_amount

innovator/templates/innovator/base.html
<!doctype html>
<html lang="en">
{% load staticfiles %}
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.82.0">
    <title>Monis project</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/album/">



<!-- Bootstrap core CSS -->
<link href="/docs/5.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
<link href="{% static 'open-iconic/font/css/open-iconic-bootstrap.css' %}" rel="stylesheet"  >
<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
<!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.0/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#7952b3">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>


  </head>
  <body>
 
    <header>

      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">

          <a class="navbar-brand" href="#">
          <img src="{% static 'logo.png' %}" height=50 width=48 class="d-inline-block alignh-top " />
          product hunt
          </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav ms-auto">

              {% block link %}
           
                 

              {% endblock %}

              <a class="nav-link" href="{% url 'login' %}" style="margin-left:4px"> logout </a>
            </div>
          </div>

        </div>
      </nav>
    </header>
 
    <div class="container">
      {% block content%}
      {% endblock %}
    </div>




<footer class="text-muted py-5">
  <div class="container text-center">
    <P>Have a happy 🌞  {% now "Y" %} </p>
  </div>
</footer>


    <script src="/docs/5.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

  </body>
</html>

innovator/templates/innovator/commentshow.html
{% extends "innovator/base.html "%}

{% block link %}
   <!--  nav bar -->
   <a class="nav-link" href="{% url 'home' 1  creator.username %}"> home  </a>

{% endblock %}

{% block content %}

 <br>
 <br>
 <div class="well-sm text-muted text-center rounded" style="background: #b3ffb3">
      <h1 style="padding: 2px 4px">  comments on  {{prod.title}} project </h1>
      <br>
 </div>
 <br>


<div class="container">
    <div class="row pt-4 ">

		{% for item in prod.comment_set.all %}

		    <div class="col-lg-8"><h5> {{item.commentz}} </h5> </div>
		    <br/>
		    <br/>
	        <div class="col-lg-4"><button type="button" class="btn btn-info">  <span class="badge">  {{item.ordusername}} : commented </span></button> </div>


		{% endfor%}
    </div>

</div>


{% endblock %}

innovator/templates/innovator/detail.html
{% extends "innovator/base.html" %}





{% block link %}
    
    <!-- Nav bar  -->

    

	{% if pname.user_type == "innovator"%}

	    <button type="button" class="btn btn-primary">logged as <span class="badge"> {{pname.username}} </span></button>

      	<a class="nav-link" href="{% url 'managetodo' product.id pname.username  %}"> Manage TODO</a>

      	<a class="nav-link" href="{% url 'manageaccount' product.id pname.username  %}"> Account </a>
        
         {% for stat in  product.encash_request_set.all %}

   			{%if stat.status == "pending"%}
      			<a class="nav-link" href="{% url 'encashstatus' product.id pname.username  %}">Encash status </a>
      		{% endif %}

      		{%if stat.status == "Encashed" %}
      		 	<a class="nav-link" href="{% url 'encashstatus' product.id pname.username  %}">Encash status </a>
      		{% endif %}

	    {% endfor %}

         


      	

      	



	{% endif  %}
     
     

	{% if pname.user_type == "ordinaryuser"%}

	<button type="button" class="btn btn-primary">logged as <span class="badge"> {{pname.username}} </span></button>

   

	{% endif  %}

	<a class="nav-link" href="{%url  'home' tokk pname %}" style="margin-left:8px"> home </a> 
    
    

{% endblock %}





{%block content%}

{% if error %}
{{ error }}
<br />
<br />
{% endif %}



<br>
<div class="well-sm text-muted text-center rounded" style="background: #b3ffb3">
      <h1 style="padding: 2px 4px"> Product  {{product.title}}  </h1>
      <br>
</div>
<br>


<div class="container">
	<div class="row">
		<div class="col-lg-5">
			<img src="{{product.image.url}}" class="img-fluid " height="325"  width="415" />
		</div>
        
	 <div class="col-lg-3">

      {% if pname.user_type == "innovator"%}

	   <button type="button" class="btn btn-info"> <a class="nav-link text-white" href="{% url  'showsubs' product.id pname.username %}"> view the subcribers  </a> </button>
      <br />
	  <br />
	  <button type="button" class="btn btn-info">
	  <a  class="nav-link text-white" href="{% url 'commentshow' product.id pname.username %}">   view comments    </a> </button>

	  <br/>
	  <br/>
	  <button type="button" class="btn btn-info">
	  <a class="nav-link text-white" href="{% url 'todoadd' product.id pname.username %}">  add todo items  </a>
	  </button>

	  <br/>
	  <br/>
	  <button type="button" class="btn btn-info">
	  <a class="nav-link text-white" href="{% url 'manageproject' product.id pname.username %}">  manage  project  </a>
	  </button>
	  <br/>
	  <br/>
	  
	  
	  {% endif  %}


	  {% if pname.user_type == "ordinaryuser"%}

		<div>
		  <a href="javascript:(document.getElementById('subcriber').submit())">
		  	<button type="button" class="btn btn-info">subcribe</button> </a>
		</div>

		<form id="subcriber" method="POST" action="{% url 'subcriber' product.id  pname.username product.postedby.username %}" >
		{% csrf_token %}
		<input type="hidden">
		</form>
        
        <br/>
         
		<a href="{% url  'commentmake' product.id pname.username  %}"> <button type="button" class="btn btn-info"> comment </button> </a>

		<br/>
        <br/>

        <a href="{% url  'tokendonate' product.id pname.username product.postedby.username  %}"> <button type="button" class="btn btn-info"> donate </button> </a>


        
        <br/>
        <br/>


	    {% endif  %}

	    <button type="button" class="btn btn-success">Posted By:<span class="badge">{{product.postedby}} </span></button>

	    <br/>
	    <br/>

	    <button type="button" class="btn btn-success">Posted on:<span class="badge">{{product.pub_date_pretty}} </span></button>

	    <br/>
	    <br/>

	    <button type="button" class="btn btn-success"> Status:<span class="badge">{{product.prostatus}} </span></button>




	    

      </div>

	</div>

</div>

<br/>
<br/>

<div class="container">
  <div class="row pt-4 px-2 rounded" style="background: lightblue">
	<p class="text-justify text-center font-weight-bold ">{{product.body}}</p>
  </div>
</div>

<br/>

<div class="container rounded" style="justify-content: center; ">
	<br>
    <div class="well-sm text-muted text-center rounded pt-1" style="background: #ffff80">
      <h1 > Todo list for   {{product.title}}  </h1>
      <br>
    </div>

       {% for todo in product.todo_set.all %}
        <div class="row "> <div class="col-lg-11" style="margin-left: 15px"> <h2>    {{todo.title}} </h2> </div> </div>
         <br>
        <div class="container">
  		<div class="row pt-4 pb-4 px-2 rounded" style="background: #fff0e6">
		 <div class="col-lg-8"><p class="text-justify text-center font-weight-bold ">{{todo.description}}</p></div>
		 <div class="col-lg-4"> <button type="button" class="btn btn-success"> Status:<span class="badge">{{todo.status}} </span></button>
         </div>

 		 <br>
 		 </div>
 		 <br>
		</div>
		<br>
       {% endfor %}
	
</div>





{% endblock %}

innovator/templates/innovator/encash.html
{% extends "innovator/base.html "%}

{% block link %}


 <a class="nav-link" href="{% url 'home' 1  creator.username %}"> home  </a>


{% endblock %}

{% block content %}

 <br>
 <br>
 <div class="well-sm text-muted text-center rounded" style="background: #b3ffb3">
      <h1 style="padding: 2px 4px">  encash page  </h1>
      <br>
 </div>
 <br>




{% if error %}
<div class="alert alert-danger" role="alert">
{{ error }}
</div>
<br />
<br />
{% endif %}


<h5 class="display-3 text-center" style="justify-content: center" >request sent to admin for approval</h5>





<a href="{% url 'detail' product.id creator.username %}" style="justify-content: center" > return to detail page </a>

{% endblock %}

innovator/templates/innovator/manageproject.html
{% extends "innovator/base.html" %}


{%block link %}

<a class="nav-link" href="{% url 'home' 1  creator %}"> home  </a>

{% endblock %}

{% block content %}
 <br>
 <br>
 <div class="well-sm text-muted text-center rounded" style="background: #b3ffb3">
      <h1 style="padding: 2px 4px">  Manage project </h1>
      <br>
 </div>
 <br>


<h5 class="display-3 text-center" style="justify-content: center" > projects posted by {{creator}} </h5>



{% for item in creator.product_set.all %}
<div class="container">
   <br/>
     
  
    
       <form method="POST" action="{% url 'manageproject' product.id creator.username %}"> 
       	{% csrf_token %}
       	{{item.title}}  
       <input name="statuschange{{item.id}}" class="btn btn-primary" type="submit" value="statuschange"  style=margin-left:10px;/>
       </form>

       {% if rstat == True and rid == item.id  %}


        



         <form method="POST" action="{% url 'manageproject' product.id creator.username %}" enctype="multipart/form-data">

         	{% csrf_token%}
            select the status of the project

         	<br>
         	<select name="updatestatus" id="todo_status">
				<option value="inprogress">inprogress</option>
				<option value="completed">completed</option>
             </select>
         	<br>

         	<input  class="btn btn-primary" type="submit" value="update" />


         





          </form>

       {% endif %}

    <br/>

</div>  
{% endfor %}


{% endblock %}